"""
Compute LD statistcs for simulated data
"""

POPS = ['YRI', 'IBS', 'CHB', 'MXB', 'MXL']


rule vcf_simulation:
    """
    The vcf for the neutral mutations.
    See the python script for details on input files.
    """
    output:
        expand('data/vcfs/sim{{sim_id}}_{population}.vcf', population=POPS),
        'data/intervals/sim_{sim_id}.tsv'
    shell:
        """
        python scripts/get_vcfs_from_simulation.py {wildcards.sim_id}
        """


rule recomb_map:
    output:
        'data/recomb_map/sim_{sim_id}-rmap.tsv'
    shell:
        """
        python scripts/get_recmap.py {wildcards.sim_id}
        """


rule get_ld_stats:
    """
    Compute LD statistics for each population
    """
    input:
        vcf='data/vcfs/sim{sim_id}_{population}.vcf',
        recomb_map='data/recomb_map/sim_{sim_id}-rmap.tsv',
        intervals='data/intervals/sim_{sim_id}.tsv'
    output:
        "results/ld_stats/{population}-region{sim_id}-ld_stats.pkl"
    shell:
        """
        python scripts/get_ld_stats.py {wildcards.sim_id} {wildcards.population}
        """
