
# where is this dir located ?
# https://github.com/santiago1234/popgene-utils

import os

CHROM = list(range(1, 23))

PATH_TO_POPGENE = "../../../../../Research/popgene-utils/"
# I assume that the msp file hsa the format mdl-{chrn}.msp.tsv
PATH_TO_XGMIX = "../../results/data/210308-local-ancestry/predictions/"


rule compute_global_ancestry_from_local:
    input:
        "../../results/data/210308-local-ancestry/predictions/mdl-{chrn}.msp.tsv"
    output:
        "data/local-chrn{chrn}.csv"
    params:
        chrn = "{chrn}",
        rscript = os.path.join(PATH_TO_POPGENE, "scripts/global-ancestry-xgmix.R")
    shell:
        """
        Rscript {params.rscript} \
            -m {input} -c {params.chrn} -o {output}
        """

rule msp_to_bed:
    input:
        os.path.join(PATH_TO_XGMIX, "mdl-{chrn}.msp.tsv")
    output:
        temp("data/bed/chr{chrn}-local-ancestry-{individual}.tsv")
    params:
        individual = '{individual}',
    shell:
        """
        python scripts/msp_to_bed.py -msp {input} -ind {params.individual} -out {output}
        """

rule merge_msp:
    input:
        expand("data/bed/chr{chrn}-local-ancestry-{{individual}}.tsv", chrn=CHROM)
    output:
        temp("data/bed/allchrn-{individual}.tsv")
    shell:
        """
        #Add the header
        head -n1 {input[0]} >{output}
        for file in {input}
        do
            tail -n+2 $file >>{output}
        done
        """

rule plot_cariotipo:
    input:
        "data/bed/allchrn-{individual}.tsv"
    output:
        "plots/{individual}-karyo.png"
    script:
        pass
