python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 70
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 60
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 80
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 70
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 60
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 90
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 65
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 90
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 61
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 71
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 62
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 72
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 62
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 72
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 71
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 66
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 91
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 81
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 61
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 91
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 82
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 92
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 67
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 92
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 63
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 73
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 63
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 83
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 73
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 93
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 64
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 74
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 64
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 84
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 74
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 94
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 69
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 94
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 68
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 93
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 66
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 76
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 75
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 75
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 65
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 85
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 65
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 95
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 70
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 95
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 66
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 71
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 86
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 96
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 76
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 96
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 87
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 72
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 77
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 97
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 67
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 68
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 67
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 68
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 78
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 88
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 78
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 98
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 97
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 77
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 69
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 79
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 89
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 99
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 74
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 99
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 73
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 98
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 69
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 79
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 71
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 80
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 90
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 70
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 80
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 70
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 0
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 75
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 91
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 81
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 71
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 76
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 72
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 81
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 82
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 72
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 92
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 82
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 2
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 1
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 77
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 74
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 74
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 73
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 83
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 73
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 3
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 78
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 93
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 83
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 45
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 75
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 50
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 65
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 45
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 4
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 84
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 94
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 79
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 84
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 50
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 60
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 60
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 75
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 46
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 76
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 51
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 66
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 46
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 61
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 47
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 77
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 52
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 67
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 47
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 62
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 52
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 51
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 61
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 76
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 62
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 77
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 48
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 78
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 53
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 68
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 48
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 63
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 53
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 63
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 49
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 69
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 79
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 54
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 49
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 64
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 54
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 64
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 79
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 78
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 80
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 50
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 51
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 50
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 55
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 65
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 65
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 70
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 80
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 55
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 57
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 81
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 56
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 66
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 71
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 51
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 56
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 66
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 81
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 82
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 57
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 52
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 67
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 72
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 82
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 52
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 53
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 83
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 58
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 67
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 73
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 58
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 68
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 68
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 53
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 83
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 59
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 74
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 31
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 84
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 27
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 60
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 59
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 69
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 69
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 84
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 54
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 55
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 85
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 54
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 35
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 75
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 60
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 70
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 55
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 70
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 85
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 61
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 76
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 86
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 62
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 72
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 87
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 57
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 61
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 71
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 86
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 71
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 56
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 56
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 87
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 62
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 57
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 72
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 77
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 63
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 78
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 58
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 73
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 88
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 59
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 89
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 64
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 79
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 59
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 74
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 58
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 88
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 63
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 73
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 40
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 40
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 45
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 55
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 89
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 74
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 64
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 41
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 28
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 56
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 57
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 42
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 42
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 47
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 41
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 46
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 48
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 43
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 58
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 43
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 44
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 49
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 44
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 59
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 50
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 45
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 45
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 46
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 46
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 60
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 61
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 51
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 48
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 63
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 48
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 47
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 52
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 47
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 53
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 62
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 55
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 50
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 65
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 50
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 64
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 49
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 54
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 66
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 49
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 51
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 53
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 34
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 52
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 52
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 67
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 57
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 56
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 51
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 53
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 58
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 55
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 0
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 45
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 59
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 69
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 54
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 54
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 56
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 33
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 68
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 2
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 47
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 57
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 34
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 1
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 46
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 35
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 48
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 3
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 49
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 59
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 4
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 61
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 6
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 51
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 50
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 60
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 58
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 5
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 8
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 53
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 63
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 62
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 7
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 52
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 9
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 54
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 64
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 66
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 11
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 10
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 55
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 65
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 12
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 57
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 67
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 56
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 58
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 35
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 15
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 13
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 30
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 25
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 15
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 14
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 59
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 69
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 68
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 20
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 30
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 25
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 30
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 20
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 36
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 36
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 16
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 31
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 26
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 37
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 17
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 32
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 27
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 17
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 16
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 21
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 21
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 31
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 26
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 32
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 22
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 37
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 32
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 22
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 38
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 18
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 33
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 28
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 18
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 39
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 19
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 34
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 29
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 19
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 23
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 33
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 33
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 38
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 23
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 24
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 24
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 29
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 39
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 34
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 40
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 20
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 35
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 30
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 20
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 41
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 21
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 36
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 31
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 21
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 25
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 35
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 25
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 30
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 40
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 36
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 26
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 31
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 36
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 41
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 26
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 27
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 42
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 37
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 32
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 22
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 23
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 38
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 37
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 27
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 32
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 37
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 22
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 42
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 33
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 23
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 38
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 28
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 43
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 33
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 38
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 28
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 43
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 39
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 24
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 34
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 39
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 29
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 34
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 39
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 29
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 24
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 44
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 44
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 5
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 10
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 90
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 95
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 0
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 15
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 5
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 0
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 30
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 31
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 91
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 14
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 24
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 19
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 11
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 91
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 6
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 96
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 1
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 16
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 12
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 92
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 7
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 97
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 31
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 1
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 6
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 6
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 96
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 91
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 32
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 17
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 2
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 2
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 7
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 27
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 13
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 8
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 93
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 98
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 14
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 10
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 18
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 3
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 33
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 8
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 3
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 3
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 43
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 94
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 99
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 4
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 9
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 19
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 9
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 4
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 34
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 10
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 15
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 10
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 20
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 0
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 95
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 5
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 35
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 16
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 76
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 5
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 96
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 97
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 1
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 6
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 96
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 21
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 11
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 11
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 6
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 36
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 7
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 7
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 17
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 2
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 12
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 22
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 12
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 7
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 37
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 97
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 86
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 18
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 15
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 98
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 13
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 3
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 8
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 23
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 13
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 28
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 8
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 38
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 4
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 44
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 19
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 99
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 4
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 14
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 11
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 40
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 25
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 40
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 35
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 25
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 9
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 24
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 9
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 14
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 39
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 30
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 35
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 45
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 30
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 40
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 45
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 20
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 0
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 5
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 25
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 41
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 15
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 10
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 40
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 36
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 26
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 46
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 36
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 41
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 26
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 26
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 46
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 41
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 31
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 1
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 41
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 16
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 21
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 16
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 11
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 32
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 12
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 17
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 17
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 42
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 12
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 98
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 85
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 48
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 8
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 37
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 49
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 49
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 27
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 32
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 42
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 27
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 42
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 82
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 33
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 47
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 37
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 29
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 47
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 42
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 22
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 2
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 18
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 23
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 13
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 38
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 28
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 28
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 48
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 38
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 43
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 43
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 18
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 43
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 13
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 39
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 9
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 29
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 19
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 14
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp_pxx 34
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 29
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 44
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 44
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 39
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 75
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 0
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 10
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 15
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 90
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 85
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 75
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 44
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 80
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 85
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 95
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 2
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 1
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 11
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 16
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 76
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 91
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 86
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 86
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 81
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 87
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 77
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 92
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 12
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 17
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 87
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 77
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 82
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 78
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 83
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 99
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 4
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 14
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 18
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 78
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 93
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 13
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 3
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 88
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 88
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 94
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 79
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 89
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 89
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 19
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 79
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 84
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 80
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 20
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 5
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 6
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 16
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 21
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 81
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 95
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 90
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 80
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 90
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 0
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 15
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 7
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 23
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 8
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 18
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 83
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 98
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 3
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 93
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 93
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 17
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 83
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 88
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 24
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 9
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 99
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 82
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 2
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 92
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 19
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 84
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 10
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 84
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 20
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 25
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 85
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 89
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 94
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 22
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 4
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 94
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 86
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 6
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 5
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 95
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 95
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 90
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 85
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 26
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 21
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 11
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 86
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 22
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 12
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 27
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 87
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 7
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 97
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 97
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 87
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 96
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 8
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 98
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 98
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 93
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 92
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 97
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 28
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 23
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 87
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 88
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 81
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 91
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 1
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 96
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 24
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PEL ppp_pxp 29
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 14
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/MXL ppp_pxp 89
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 9
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 88
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppp_pxp 94
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ccx_xxp 99
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 99
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_ccx_xxp 89
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/CLM ppp_pxp 92
python admixture-inference.py ../../../analysis-doc/210514-ProcessXGMixOutForTracts/data/3-pops/tracts/PUR ppx_xxp 13
