'''
Demographic inference pipeline
'''

### *************************************************** ####
### ************* MODEL INFERENCE ********************* ####
### *************************************************** ####

def get_mL_file(wildcards):
    if wildcards.varcat == 'intronic':
        return '../../data/220113-ConstructBoostrapedDatasets/data/whole-genome/mL-introns.txt'
    else:
        return '../../data/220113-ConstructBoostrapedDatasets/data/whole-genome/mL-' + wildcards.varcat + '.txt'


rule infer_OOA:
    input:
        model = 'data/OOA-model.yml',
        parameters = 'data/OOA-parameters.yml',
        mL = get_mL_file,
        data = '../../data/220113-ConstructBoostrapedDatasets/data/whole-genome/spectrum-cat_{varcat}.pkl.gz'
    output:
        'results/best-guest-OOA-{varcat}.yml',
        'results/best-guest-OOA-{varcat}-bestparameters.csv'
    params:
        outprefix = 'results/best-guest-OOA-{varcat}'
    shell:
        '''
        python scripts/infere-ooa-model.py \
            {input.model} {input.parameters} \
            {input.mL} {input.data} \
            {params.outprefix}
        '''


rule make_NAT_EXPANSION_FILES:
    input:
        ooa_best = 'results/best-guest-OOA-{varcat}.yml',
        nat_specific_mdl = 'data/NAT-EXPANSION-files/NatExpansion-params.txt',
        nat_parameters = 'data/NAT-EXPANSION-files/NatExpansion-options.yml'
    output:
        model = 'data/NAT-EXPANSION-MODELS/NAT-EXPANSION-model-{varcat}.yml',
        parameters = 'data/NAT-EXPANSION-MODELS/NAT-EXPANSION-parameters-{varcat}.yml'
    shell:
        '''
		#Make model yml file
		sed -n "1,35p" {input.ooa_best} >{output.model}
		cat {input.nat_specific_mdl} >>{output.model}
		sed -n "36,44p" {input.ooa_best} >>{output.model}
		#Make params file
		sed -n "1,3p" {input.nat_parameters} >{output.parameters} 
		python scripts/get-CHB-start-time.py {input.ooa_best} >>{output.parameters}
		sed -n "5,21p" {input.nat_parameters} >>{output.parameters}
        '''


rule infer_NAT_EXPANSION:
    input:
        model = 'data/NAT-EXPANSION-MODELS/NAT-EXPANSION-model-{varcat}.yml',
        parameters = 'data/NAT-EXPANSION-MODELS/NAT-EXPANSION-parameters-{varcat}.yml',
        mL = get_mL_file,
        data = '../../data/220113-ConstructBoostrapedDatasets/data/whole-genome/spectrum-cat_{varcat}.pkl.gz'
    output:
        'results/best-guest-NAT-EXPANSION-{varcat}.yml',
        'results/best-guest-NAT-EXPANSION-{varcat}-bestparameters.csv'
    params:
        outprefix = 'results/best-guest-NAT-EXPANSION-{varcat}'
    shell:
        '''
        python scripts/infere-NAT-EXPANSION-model.py \
            {input.model} {input.parameters} \
            {input.mL} {input.data} \
            {params.outprefix}
        '''


### *************************************************** ####
### ************* MODEL UNCERTAINTY ******************* ####
### *************************************************** ####


#rule FULL_model_paramters_file:
#    input:
#        ooa_params = 'data/OOA-parameters.yml',
#        nat_params = 'data/NAT-EXPANSION-MODELS/NAT-EXPANSION-parameters-{varcat}.yml'
#    output:
#        'data/FULL-MODEL-options/full-mdl-{varcat}.yml'
#    shell:
#        '''
#        # Add OOA params
#        sed -n "1,94p" {input.ooa_params} >{output}
#        # Add NAT expansion params
#        sed -n "2,21p" {input.nat_params} >>{output}
#        # Add the constrains
#        sed -n "95,99p" {input.ooa_params} >>{output}
#        '''


rule boostra_replicates:
    input:
        sfs_path = directory('../../data/220113-ConstructBoostrapedDatasets/data/jSFS/spectrums/'),
        mL_path = directory('../../data/220113-ConstructBoostrapedDatasets/data/mL-noncoding/mLs/')
    output:
        'data/boostrap-replicates/{varcat}-breplicates.pkl'
    shell:
        """
        python scripts/construct-boostraped-replicates.py \
            {input.sfs_path} {input.mL_path} \
            {wildcards.varcat} {output}
        """
